package org.example.latch;

public enum RocketDetail {

    ENGINE,
    CONTROL_AND_GUIDANCE_SYSTEM,
    AERODYNAMIC_ELEMENTS,
    SPACE_VEHICLE,
    INSTRUMENT_COMPARTMENT,
    OXIDIZER_TANK,
    FUEL_TANK,
    PUMPS,
    COMBUSTION_CHAMBER,
    NOZZLE


}
